### ISSUE TITLE
Java 11 support?

### ISSUE THREAD

**Issue by oobles** [datastax/native-protocol#31]
I've been upgrading a project to use Java 11.  As part of this we upgraded to use java-driver-core 4.2.0.  When starting the application we get this error:

Error occurred during initialization of boot layer
java.lang.module.FindException: Unable to derive module descriptor for /Users/.../com.datastax.oss/native-protocol/1.4.6/.../native-protocol-1.4.6.jar
Caused by: java.lang.IllegalArgumentException: native.protocol: Invalid module name: 'native' is not a Java identifier

Environment is osx with AdoptOpenJdk 11.0.4.hs

**Comment by oobles** [comment]
Related to  https://stackoverflow.com/questions/46501388/unable-to-derive-module-descriptor-for-auto-generated-module-names-in-java-9

The easiest answer is to add in an Automatic-Module-Name as described by the link.

**Comment by oobles** [comment]
I notice that there's a pull request to add the Automatic-Module-Name (https://github.com/datastax/native-protocol/pull/30).  For anyone waiting for that to be published, the workaround is to add it to the jar manually...

jar -xf ../native-protocol-1.4.6.jar
sed -ie '/Created-By:/a\'$'\n''Automatic-Module-Name:com.datastax.oss.protocol\n' MANIFEST.MF
jar -cfm ../native-protocol-1.4.6.jar META-INF/MANIFEST.MF .

**Comment by olim7t** [comment]
Hi,
Yes, I was going to mention that pull request. We'll address that in 4.3.0, I've created [JAVA-2435](https://datastax-oss.atlassian.net/browse/JAVA-2435) in Jira to track it.
